// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBORG8x41f3Fap7xGr06_FMwz_QfM5eQo',
    appId: '1:217656790224:web:8cd0c4d4d37826c25962d5',
    messagingSenderId: '217656790224',
    projectId: 'estoreapp-ab693',
    authDomain: 'estoreapp-ab693.firebaseapp.com',
    storageBucket: 'estoreapp-ab693.appspot.com',
    measurementId: 'G-YJCLH0X9CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADWTapBGv8A65cEQsYPj6fDlGqCiLcYaE',
    appId: '1:217656790224:android:74df28d5236d0a145962d5',
    messagingSenderId: '217656790224',
    projectId: 'estoreapp-ab693',
    storageBucket: 'estoreapp-ab693.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLMLLI0Qk_lCdbmDL0Zsi7M_W_BIX2X8',
    appId: '1:217656790224:ios:047c1109793cb91b5962d5',
    messagingSenderId: '217656790224',
    projectId: 'estoreapp-ab693',
    storageBucket: 'estoreapp-ab693.appspot.com',
    iosClientId: '217656790224-khr67k958h6d057nst6rvv216ke5sjoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLMLLI0Qk_lCdbmDL0Zsi7M_W_BIX2X8',
    appId: '1:217656790224:ios:047c1109793cb91b5962d5',
    messagingSenderId: '217656790224',
    projectId: 'estoreapp-ab693',
    storageBucket: 'estoreapp-ab693.appspot.com',
    iosClientId: '217656790224-khr67k958h6d057nst6rvv216ke5sjoq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
